[package]
name = "juju"
version = "0.1.0"
description = "A resident Windows developer toolbox"
authors = ["qlxsply"]
edition = "2021"

[lib]
name = "juju_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
