<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\..\my_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\my_icon.ico" Link="my_icon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
